spring.application.name=educhain

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size = 10MB
file.upload-dir=src/main/resources/static/uploads
spring.web.resources.static-locations=classpath:/static/
file.video.upload-dir=src/main/resources/static/video

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true

base.url.verify=${BASE_URL_VERIFY}
base.url.reset.password=${BASE_URL_RESET_PASSWORD}
base.url.default.avatar=${BASE_URL_DEFAULT_AVATAR}
base.url.default.blogImage=${BASE_URL_DEFAULT_BLOG_IMAGE}
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox

contract.edc.address=${EDC_CONTRACT_ADDRESS}
contract.certification.address=${CERTIFICATION_CONTRACT_ADDRESS}
infura.api.key=${INFURA_API_KEY}
private.key=${WALLET_PRIVATE_KEY}
